<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE application SYSTEM "..\schema\AppNavModel.dtd"> -->
<!DOCTYPE application [
<!-- nl= natural language expression id= unique id -->
<!ELEMENT vsn (role)>
<!ATTLIST vsn
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED
  aka CDATA #REQUIRED
  path CDATA #REQUIRED
  nl CDATA #REQUIRED>

<!ELEMENT role (attribute)>
<!ATTLIST role
  xmlns CDATA #FIXED ''
  nl CDATA #REQUIRED>

<!ELEMENT attribute (does)+>
<!ATTLIST attribute
  xmlns CDATA #FIXED ''
  how CDATA #REQUIRED
  nl NMTOKEN #REQUIRED>

<!ELEMENT goal EMPTY>
<!ATTLIST goal
  xmlns CDATA #FIXED ''
  nl CDATA #REQUIRED>

<!ELEMENT does (intent)>
<!ATTLIST does
  xmlns CDATA #FIXED ''
  how CDATA #IMPLIED
  nl CDATA #REQUIRED
  id ID #REQUIRED
  lbl CDATA #IMPLIED
  onBelief CDATA #IMPLIED>

<!ELEMENT intent (strategy)+>
<!ATTLIST intent
  xmlns CDATA #FIXED ''
  nl CDATA #REQUIRED>

<!ELEMENT strategy (theme+|visit+)>
<!ATTLIST strategy
  xmlns CDATA #FIXED ''
  id ID #REQUIRED
  nl CDATA #REQUIRED>

<!ELEMENT theme (visit)+>
<!ATTLIST theme
  xmlns CDATA #FIXED ''
  lbl CDATA #REQUIRED
  nl CDATA #REQUIRED>

<!ELEMENT visit (domain+,(action,query)?)>
<!ATTLIST visit
  xmlns CDATA #FIXED ''
  lbl CDATA #IMPLIED
  nl CDATA #REQUIRED>

<!ELEMENT domain (evidence*,(action|query)*)>
<!ATTLIST domain
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED
  lbl CDATA #IMPLIED
  nl CDATA #IMPLIED
  nl CDATA #IMPLIED>

<!ELEMENT evidence EMPTY>
<!ATTLIST evidence
  xmlns CDATA #FIXED ''
  nl CDATA #IMPLIED
  type NMTOKEN #REQUIRED>

<!ELEMENT query EMPTY>
<!ATTLIST query
  xmlns CDATA #FIXED ''
  natural_question CDATA #IMPLIED
  nl CDATA #REQUIRED
  type NMTOKEN #IMPLIED>

<!ELEMENT action (action*,evidence*,query*)>
<!ATTLIST action
  xmlns CDATA #FIXED ''
  id ID #IMPLIED
  lbl CDATA #IMPLIED
  nl CDATA #REQUIRED  
  type NMTOKEN #IMPLIED>
  
]>
<!-- action type c = critical publication, type t = tactical publication -->
<vsn id="root_version_2" nl="Reviving Modernism"
  aka="Modernist revival- celebrating the certainty of the scientific method and the life space provided by its incompleteness. 
Interpreting this into contexts as long running projects"
  path="implies Romanticism over conservative modernsit values, critical of postmodernism, which implies optimism on the human condition and faith">
  <role nl="A critical agent">
    <attribute nl="humility" how="a project running for finite time">
      <does id="insp" nl="Defending the Idea of Modernist Revival, Scientific Realism" onBelief="There are desirable actions that arise in the right environment">
        <intent nl="create an optimal environment">
          <strategy id="abt" nl="being honest and clear, some kind of a charter">
            <theme lbl="Our Intent- About Us" nl="about us">
              <visit lbl="Why this Project" nl="Why this is zeigteist">
                <domain id="abt_zei_cont" lbl="" nl="contemproary issues with knowledge and justifying intervention">
                  <action type="crt" nl="Why Projects like this should exist"></action>
                </domain>
                <domain id="abt_just" nl="justifying modernity, science and Objective truths">
                  <action type="crt" nl="Why the scientific method and modernity should be preserved">
                    <query natural_question="Is scientific Method then holy?" nl="link::abt_zei_spr_1"></query>
                  </action>
                  <action type="crt" nl="Post Modernist, open loop crisis"></action>
                  <action type="crt" nl="Formalisms are comfortable, non intrusive"></action>
                  <action type="tct" nl="Holism, thinking science with culture- and never acting on such paradigm"></action>
                  <action type="tct" nl="Domain Transforms and Thermodynamic Interpretations"></action>
                </domain>
                <domain id="abt_zei_spir" nl="Defend the zeigteist from normative points">
                  <action type="tct" nl="Uncertainty Principles in Science-Undecidability provides lifespaces"></action>
                  <action type="tct" nl="Aesthetics in Scientific Realism"></action>
                  <action type="tct" nl="Normative Intent in Instrumentalism"></action>
                  <action type="tct" nl="Importance of Agency and Action"></action>
                  <action type="tct" nl="Why analysis is the only epistemological possibility to appreciate teleos"></action>
                </domain>
                <domain id="abt_zei_intui" nl="There is no way to defend the zeigtiest but never mind">
                  <action type="tct" nl="Epistemological limits and hence presenting pieces of ideas for Intuitive Embrace"></action>
                  <action type="tct" nl="Circular truth of zeigteist - teleos and presence of supreme order"></action>
                  <action type="tct" nl="Embracing contradictions-why selfless love is good, loosing ego is good"></action>
                </domain>
                <domain id="abt_just" nl="Justifying this enterprise howsoever humble">
                  <action nl="Is progress disrupted by modernist nostalgia"></action>
                  <action nl="Is statistical computing misleading, or atleast need critques (norvig Chomsky debates)"></action>
                  <action nl="Slowing down adversarial Search and Transforming it to other modes">
                    <query natural_question="what is the science behind the slow down logic?" nl="link::"></query>
                  </action>
                </domain>
              </visit>
            </theme>
            <theme lbl="More on the Belief" nl="All Beliefs deserve peaceful demonstration, which we do here">
              <visit nl="what this is not">
                <domain id="abt_not" nl="churches and cults">
                  <action type="crt" nl="Why ideas are not going to be final, the synthetic nature of truths"></action>
                  <action type="crt" nl="We are going to run for 200 years, because state transitions should be definite"></action>
                  <action type="crt" nl="Campaigns to align with humility"></action>
                  <query natural_question="And what are those compaigns?" nl="link::to campaigns list"></query>
                </domain>
              </visit>
              <visit nl="Notes on Founding Ideas and Inspirations">
                <domain id="abt_cmp" nl="Theme of the Campus">
                  <action type="crt" nl="Why University towns make sense"></action>
                  <action type="crt" nl="Recursive Human structures make sense"></action>
                </domain>
                <domain id="abt_fnd" nl="founding ideas">
                  <action type="crt" nl="A critical institution that is best defined as Nostalgic"></action>
                  <action type="crt" nl="embracing the contradition of scinetific method and its incompleteness"></action>
                  <action type="crt" nl="Modernism- presenting rigid systems distinct from the cushy life spaces"></action>
                  <action type="crt" nl="Post modernist critique and modernist revival"></action>
                  <action type="crt" nl="Scientific Method as being liberating"></action>
                  <action type="crt" nl="Romanticism and optimism over the redemption from human condition"></action>
                  <action type="crt" nl="The redeemer, love and faith"></action>
                  <action type="crt" nl="busting the right left divide"></action>
                  <action type="crt" nl="Conservatism, virtue, going slow, peace"></action>
                  <action type="crt" nl="Definite transitions preferred over open loop continuums"></action>
                  <action type="crt" nl="Peace and Gandhian thought- never be dogmatic just as with science"></action>
                </domain>
                <domain id="abt_fnd" nl="Literature">
                  <action type="crt" nl="Respecting the formalisms of Chomsky, preferring algorithms as midway between math and normative world"></action>
                  <action type="crt" nl="Respecting the non technical fix for wicked domains-Churchman, Rittel and Malthus"></action>
                  <action type="crt" nl="View points of Judea Pearl, Bill Gates and Hawking"></action>
                  <action type="crt" nl="Science as pillar of enlightment- Cartesian tradition of goodness and soul"></action>
                  <action type="crt" nl="The way of the east- of rituals, harmony as arising naturally in the meantime"></action>
                  <action type="crt" nl="Zen-intuition"></action>
                </domain>
                <domain id="abt_fnd" nl="Critical Literature">
                  <action type="crt" nl="Bauman on Modernity"></action>
                  <action type="crt" nl="Frankfurt school of critical studies"></action>
                  <action type="crt" nl="Rousseauian Romantic Schools on rejecting objectivism"></action>
                  <action type="crt" nl="Conservatism (in preserving modernity) as regressive"></action>
                  <action type="crt" nl="Are preservational, ideological cults needed?"></action>
                </domain>
              </visit>
            </theme>
          </strategy>
        </intent>
      </does>
      <does id="compExp" nl="Providing a Resource Base of Tools and Techniques" onBelief="Techniques complementing inspiration can defer the tragedy of the commons indefinitely">
        <intent nl="To help visitors to initiate conversations and engage in further research along these topics in order to distribute these techniques as part of the mission">
          <strategy id="infosci" nl="Providing a Resource base for approaching the abstract ideas">
            <theme lbl="Expository Essays in Information Sciences " nl="Information Theory">
              <visit lbl="A MetaPhysical Overview" nl="A Metaphysical Overview">
                <domain id="infosci_meta" nl="Entropy and Thermodynamics">
                  <action type="tct" nl="Energy Problem"></action>
                  <action type="tct" nl="Structure and life"></action>
                  <action type="tct" nl="Countering Entropy by internalization, recursion"></action>
                  <action type="tct" nl="Entropy as Intelligence"></action>
                  <action type="tct" nl="the seven unsolvable, undecidable problems"></action>
                </domain>
              </visit>
              <visit nl="Computation in principle">
                <domain id="infosci_compu" nl="Information Theory">
                  <action type="tct" nl="Computing as universal"></action>
                  <action type="tct" nl="Computing hardness and limitation"></action>
                  <action type="tct" nl="Inevitability of Compression and recursion as compression"></action>
                  <action type="tct" nl="Computer as transducer, as language, a theorem generator"></action>
                </domain>
              </visit>
              <visit nl="Computation in Nature">
                <domain id="infosci_compu" nl="Information Theory">
                  <action type="tct" nl="Evolution and Computing-Simulation and Algorithms"></action>
                  <action type="tct" nl="Mathematical Realism"></action>
                  <action type="tct" nl="Recursion in nature, the structure-pseudorandomness dilemma"></action>
                  <action type="tct" nl="Optimization in nature"></action>
                </domain>
              </visit>
              <visit nl="Computation in Normalized sense">
                <domain id="infosci_compu" nl="Normative-altruistic stances">
                  <action type="tct" nl="Formal Nature of Problem Solving, Entropy"></action>
                  <action type="tct" nl="Scientific method and open loop computing"></action>
                  <action type="tct" nl="Normative Stances-Rousseau Evolution versus Cognition"></action>
                  <action type="tct" nl="Mueller's arms of civilization and computing"></action>
                  <action type="tct" nl="Game Theory versus Cooperation"></action>
                </domain>
                <domain id="infosci_compu" nl="Limitations of Computational Problem solving">
                  <action type="tct" nl="Fundamental Undecidability problems"></action>
                  <action type="tct" nl="Transaction cost, refelxivity, wicked problems, tragedy of commons"></action>
                </domain>
                <domain id="busi_compu" nl="Normative-Business Stances">
                  <action type="tct" nl="A political history of computing"></action>
                  <action type="tct" nl="Rigid Classical EDP Style Computing and the Hippies"></action>
                  <action type="tct" nl="Agile and OpenSource"></action>
                  <action type="tct" nl="Design based Computing, mythical man month"></action>
                  <action type="tct" nl="Businesses as Networks"></action>
                  <action type="tct" nl="Businesses as Deterministic Tools of Civilization"></action>
                </domain>
              </visit>
              <visit nl="Computation and Design">
                <domain id="design_compu" nl="Information Theory">
                  <action type="tct" nl="A political history of computing"></action>
                  <action type="tct" nl="Rigid Classical EDP Style Computing and the Hippies"></action>
                  <action type="tct" nl="Design is Political, Slack in computational determinism"></action>
                  <action type="tct" nl="Design is An Art, the Antisystems- Art pour le Art"></action>
                </domain>
              </visit>
              <visit lbl="Recent Developments" nl="A descriptive (non critical view) of New age solutions">
                <domain id="literature on crises" nl="Computing">
                  <action type="tct" nl="BlockChain"></action>
                  <action type="tct" nl="IOT"></action>
                  <action type="tct" nl="Digital Revolution"></action>
                  <action type="tct" nl="Machine Learning"></action>
                  <action type="tct" nl="Full Automation and Emergent Structrures"></action>
                </domain>
              </visit>
            </theme>
            <theme nl="Technology and Tools" lbl="Open Source Projects in Computing">
              <visit nl="Open Source Projects-for distribution">
                <domain id="verification" nl="Software for Rigourous Verification">
                  <action nl="SPO-Documentation"></action>
                  <action nl="Techniques for Verifiability"></action>
                </domain>
                <domain id="NP Hard Problems" nl="Classical Algorithms">
                  <action nl="Heuristic Allocator"></action>
                  <action nl="Essays on Heuristic Algorithms"></action>
                </domain>
                <domain id="MiddleWare" nl="connecting language paradigms">
                  <action nl="TRS-Excel Restful Services"></action>
                </domain>
                <domain id="Small FootPrint Servers" nl="Small FootPrint Servers">
                  <action nl="A small CMS"></action>
                </domain>
                <domain id="Small FootPrint Servers" nl="Small FootPrint Servers">
                  <action nl="A small CMS"></action>
                </domain>
              </visit>
              <visit nl="Technology Topics">
                <domain id="Java" nl="Java-Essays on New Ideas">
                  <action nl="Dependency Injection without Spring"></action>
                  <action nl="Java as a Functional Language"></action>
                </domain>
                <domain id="Integrating Languages" nl="Integrating languages">
                  <action nl="Groovy Templating"></action>
                  <action nl="CPython"></action>
                  <action nl="Hypothesis confirmation with Scala"></action>
                </domain>
                <domain id="Review of Technologies" nl="Review of Technologies">
                  <action nl="Spring Boot"></action>
                  <action nl="R Studio"></action>
                </domain>
              </visit>
            </theme>
          </strategy>
        </intent>
      </does>
      <does id="compCrit" nl="Resource Base of Critical Views on Computing" onBelief="A Critical Analysis helps in better positioning computing as a tool for humanity">
        <intent nl="To initiate collaboration with visitors on these critical areas">
          <strategy id="critComp" nl="Resource Base for approaching critical ideas">
            <theme lbl="Critical Essays on AI and ML" nl="The AI Safety Issue ">
              <visit lbl="Computational Crisis" nl="Sciences">
                <domain id="literature on crises" nl="Computing">
                  <action type="tct" nl="Review of Turing and Church Hypothesis"></action>
                  <action type="tct" nl="Bostrom-Critique of the Simulation Argument"></action>
                  <action type="tct" nl="Are we living in a simulation?"></action>
                </domain>
              </visit>
              <visit lbl="New Fangled Solutions and Eternal Problems" nl="A critical view of New age solutions">
                <domain id="literature on crises" nl="Computing">
                  <action type="tct" nl="BlockChain"></action>
                  <action type="tct" nl="IOT"></action>
                  <action type="tct" nl="Digital Revolution"></action>
                  <action type="tct" nl="Machine Learning"></action>
                  <action type="tct" nl="Full Automation and Emergent Structrures"></action>
                </domain>
              </visit>
              <visit nl="Critique of Direct Computing">
                <domain id="infosci_compu" nl="Information Theory">
                  <action type="tct" nl="Simulation versus Algorithm"></action>
                  <action type="tct" nl="Critique of Cybernetics"></action>
                  <action type="tct" nl="Decisive, Static problem solving"></action>
                  <action type="tct" nl="Dynamic Models and reconcillation using the scientific method"></action>
                  <action type="tct" nl="The Libertarian Dream quashed by pervasive computing"></action>
                  <action type="tct" nl="Domain Transforms into Rise of the machines scenarios"></action>
                </domain>
                <domain id="infosci_norm" nl="Meaning, verifiability and other human considerations of computing">
                  <action type="tct" nl="Alternate courses to Evolution, transforms and virtue (slowing down)"></action>
                  <action type="tct" nl="Meaning, Control and Experience in terms of knowledge"></action>
                  <action type="tct" nl="Verifiability, Blackboxes"></action>
                  <action type="tct" nl="Computing as phenomenon or as an Experiment- the choice"></action>
                </domain>
              </visit>
            </theme>
            
          </strategy>
        </intent>
      </does>
      <does id="SciMethod" nl="Epistemology and the Scientific Method" onBelief="We attempt to provide a way to celebrate the mundane so that we are not lost in transhumanism">
        <intent nl="Avoiding Transhumanism, by contentment">
          <strategy id="epistem" nl="Understanding the limits of knowing and problem solving">
            <theme lbl="Epistemology and the Scientific Method" nl="Epistemology and Education">
              <visit nl="Epistemology and the Scientific Method">
                <domain id="infosci_human" nl="Disciplines Visited for the pleasure of it">
                  <action type="crt" nl="Education as being over and above information"></action>
                  <action type="crt" nl="Complexity of Representation and Existence"></action>
                  <action type="crt" nl="Problem solving limited by our ability to know if we have solved it"></action>
                  <action type="crt" nl="Verification and Synthetic truth generation as integral to agency"></action>
                  <action type="crt" nl="Nature of Mathematics"></action>
                  <action type="crt" nl="Classical Mechanics, Empiricism"></action>
                  <action type="crt" nl="Chemistry"></action>
                </domain>
              </visit>
              <visit nl="the gift of undecidable problems">
                <domain id="infosci_incompletness" nl="Where our epistemology ends and which belief we happily embrace">
                  <action type="crt" nl="The idea of love, truth and beauty"></action>
                </domain>
              </visit>
              <visit lbl="Humanities- problem solving methods" nl="Solving Problems while remaining humans, literature">
                <domain id="ivorytowers_peerworks" nl="Management">
                  <action type="crt" nl="Soft Sciences Economics et al"></action>
                  <action type="tct" nl="Review of Churchman Work"></action>
                  <action type="tct" nl="Review of Baumann's Work"></action>
                  <action type="tct" nl="Marx and Keynes"></action>
                  <action type="tct" nl="Review of Richard Thaler's Work"></action>
                  <action type="tct" nl="Works of Tolstoy- Anna Kareinena, art as an expression of truths"></action>
                  <action type="tct" nl="REview of Chomsky-Norvig Debates"></action>
                </domain>
                <domain id="The domain of law">
                  <action type="tct" nl="Law and truth discovery"></action>
                  <action type="tct" nl="Law and Corporate Governance"></action>
                  <action type="tct" nl="The due process of Law"></action>
                </domain>
              </visit>
            </theme>
          </strategy>
          <strategy id="moral_ref" nl="now that we know problem solving is constrained, we can think of moral traditions">
            <theme nl="malthusian traditions" lbl="Malthusian tradition">
              <visit nl="A look at the tragedy of commons and reversed positions">
                <domain id="Tragedy of commons">
                  <action nl="Malthus, Rittel and HArdin"></action>
                  <action nl="Thaler et al"></action>
                  <action nl="Inevitable Moral referral"></action>
                </domain>
              </visit>
            </theme>
          </strategy>
          <strategy id="ivorytowers" nl="Rigourous Discipline rather than speculation and revelation">
            <theme lbl="Celebration of the unassuming fellow- Method" nl="Methods over Dogma : Celebrating the Scientific Method">
              <visit nl="the idea and comfort of rigour">
                <domain id="rigour" nl="Rigourous Discipline rather than speculation and revelation">
                </domain>
              </visit>
            </theme>
          </strategy>
          <strategy id="scimethod" nl="Intellectual Reflection of Aesthetics">
            <theme lbl="The Scientific Method and its Wisdom" nl="Appreciating the scientific method in its symmetry and incompleteness">
              <visit lbl="Tradition of the Scientific Method" nl="Appreciate the Scientific method and its tradition">
                <domain id="scimethod_hist" nl="history of European enlightenment">
                  <evidence type="newsfeed" nl="extLinks:Books on European Enlightenment"></evidence>
                  <evidence type="story" nl="link::Stories in Educational Campaigns"></evidence>
                  <evidence type="literature" nl="extLinks::Open Source Literature"></evidence>
                  <action type="tct" nl="the state of nature and the redemption"></action>
                  <action type="crt" nl="Avoiding Eurocentric views"></action>
                  <action type="crt" nl="Ancient Indian and Arabic scientific themes"></action>
                  <query natural_question="is no science good?" nl="link::how zen is good :: aes_zen_1"></query>
                </domain>
                <domain id="scimethod_global_hist" nl="history of worldwide science">
                  <action type="crt" nl="Human Progress is Universal and convergant"></action>
                </domain>
              </visit>
              <visit nl="Merits and Demerits">
                <domain id="scimethod_dtl" nl="understanding the experiment, observe, model cycle">
                  <action type="tct" nl="on intrinsic merits with respect to human psyche"></action>
                </domain>
                <domain id="crit_sci_meth" nl="Shortcomings of the method">
                  <action id="sci_mtd_at1" type="tct" nl="on how analysis is meritorious but could be illusiorily fogged"></action>
                  <action type="crt" nl="suggesting post modernity's illusion with being fluidic">
                    <query type="natural_question" nl="link to:: Why Zeigteist"></query>
                  </action>
                  <action type="crt" nl="the boredom with scientific method how handled">
                    <query type="natural_question" nl="link to:: Deterministic defense to Zeigteist"></query>
                  </action>
                </domain>
              </visit>
              <visit nl="Incompleteness and its Aesthetics- Appreciating Incompleteness in the right spirit">
                <domain id="sci_aesthetics_uncert" nl="the timeless mood over uncertainty">
                  <evidence type="newsfeed" nl="extLinks:news on how IT might get dangerous"></evidence>
                  <evidence type="story" nl="link::Stories in the campaigns"></evidence>
                  <evidence type="literature" nl="extLinks::Open Source Literature"></evidence>
                  <action type="tct" nl="did the ancients (science guys ) accept the incompleteness">
                    <query natural_question="how it could be got wrong?link::sci_mtd_at1" nl="link to the modern illusion"></query>
                  </action>
                  <action type="tct" nl="Modern stance on uncertainty" />
                  <action type="crt" nl="Uncertainty Celebrated in Agile, Soft Computing">
                    <query natural_question="whats wrong?link::sci_mtd_at1" nl="link to the modern illusion"></query>
                    <query natural_question="was it done right?link::?" nl="link to eastern idea of scientific method"></query>
                  </action>
                  <action type="crt" nl="Uncertainty Celebrated in Culture">
                    <query natural_question="whats wrong?link::sci_mtd_at1" nl="link to the modern illusion"></query>
                  </action>
                </domain>
                <domain id="sci_aesthetics_zen" nl="Zen, Harmony and Resignation">
                  <action nl="How east appreciated uncertainty"></action>
                  <action nl="Hermeneutic or Natural Truths"></action>
                  <action nl="Pessimism and the Survival Question">
                    <query natural_question="are we endangering future of humanity?" nl="link::abt_just"></query>
                  </action>
                </domain>
                <domain id="sci_aesthetics_critic" nl="Critical Truth Discovery">
                  <action nl="Intuition as path to critical truth">
                    <query natural_question="do we do it?" nl="link::abt_"></query>
                  </action>
                  <action nl="Why judges and doctors are revered"></action>
                  <action nl="Chivalry and Romanticism"></action>
                  <action nl="Gandhian Theme"></action>
                  <action nl="Endearing Flicks and Works of Literature"></action>
                  <action nl="Natural World, Aesthetics and Right to live"></action>
                </domain>
                <domain id="sci_aesthetics_agency" nl="Agency and Intentionality">
                  <action nl="Human Organizations as Transforms"></action>
                  <action nl="Intentional Communities Critical Examination"></action>
                  <action nl="Fighting Evolution and the Exponent"></action>
                  <action nl="Why the fight and is it winnable"></action>
                  <action nl="Extended Agency and how retention of agency is faith">
                    <query natural_question="how to embrace contradiction" nl="link::abt_zei"></query>
                  </action>
                </domain>
              </visit>
            </theme>
          </strategy>
        </intent>
      </does>

      <does id="CampaignMeta" lbl="Nature of our Campaigns" nl="Form Campaigns" how="Run Campaigns" onBelief="There is a teleos to nurture right environment">
        <intent nl="Can be humble promotor of certain actions, not as a sweeping campaign, more like how we take care of friends">
          <strategy id="camp_defwell" nl="Define Campaigns well">
            <theme lbl="Campaigns Overview" nl="A Walkthrough of our campaigns">
              <visit nl="Out of the Blue picks of campaigns">
                <domain id="camp_defwell_howchosen" nl="Conception of campagins: Intellectual and Aesthetic Reflection in discussions as Hymns">
                  <query natural_question="how are campaigns chosen?" nl="link::abt_camp"></query>